name: Build

on:
  push:
    branches: [main, develop, serenity, euphoria, feat/cicd]

jobs:
  build:
    runs-on: [self-hosted, aura]
    steps:
      - uses: actions/checkout@v3
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)"  >> $GITHUB_OUTPUT  
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/erascope:cicd_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
      - name: Build the Docker image and push it to the registry
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.KEY_NPM_RC }}
        run: |
          chmod 777 -R ./ci
          ./ci/build.sh

