name: Build

on:
  workflow_dispatch:
  push:
    branches: [main, develop, serenity, euphoria, feat/cicd]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  updateManifest:
    uses: ./.github/workflows/update_manifest.yml
    secrets: inherit